export default [
  {
    id: 9,
    category: "General Knowledge",
    description: "",
    img: "/icons/neurology_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.png",
  },
  {
    id: 10,
    category: "Entertainment: Film",
    description: "",
    img: "/icons/live_tv_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 11,
    category: "entertainment: Books",
    description: "",
    img: "/icons/book_5_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 12,
    category: "Entertainment: Music",
    description: " ",
    img: "/icons/library_music_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 13,
    category: "Entertainment: Musicals & Theatres",
    description: " ",
    img: "/icons/theater_comedy_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 14,
    category: "Entertainment: Television",
    description: " ",
    img: "/icons/live_tv_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 15,
    category: "Entertainment: Video Games",
    description: "",
    img: "/icons/stadia_controller_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 16,
    category: "Entertainment: Board Games",
    description: "",
    img: "/icons/widgets_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 17,
    category: "Science & Nature",
    description: " ",
    img: "/icons/nature_people_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 18,
    category: "Science: Computers",
    description: " ",
    img: "/icons/code_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 19,
    category: "Science: Mathematics",
    description: " ",
    img: "/icons/calculate_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 20,
    category: "Mythology",
    description: " ",
    img: "/icons/globe_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 21,
    category: "Sports",
    description: " ",
    img: "/icons/exercise_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 22,
    category: "Geography",
    description: " ",
    img: "/icons/globe_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 23,
    category: "History",
    description: "",
    img: "/icons/newsstand_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 24,
    category: "Politics",
    description: " ",
    img: "/icons/gavel_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 25,
    category: "Art",
    description: " ",
    img: "/icons/brush_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 26,
    category: "Celibrities",
    description: " ",
    img: "/icons/local_activity_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 27,
    category: "Animals",
    description: " ",
    img: "/icons/pets_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 28,
    category: "Vehicles",
    description: " ",
    img: "/icons/auto_towing_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 29,
    category: "Entertainment: Comics",
    description: " ",
    img: "/icons/animated_images_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 30,
    category: "Science: Gadgets",
    description: " ",
    img: "/icons/devices_wearables_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 31,
    category: "Entertainment: japanese Anime & Manga",
    description: " ",
    img: "/icons/language_chinese_cangjie_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
  {
    id: 32,
    category: "Entertainment: Cartoon & Animations",
    description: " ",
    img: "/icons/animated_images_24dp_C8E2E9_FILL0_wght400_GRAD0_opsz24.svg",
  },
];
